services:
  sgdb:
    image: postgres:17.4
    restart: always
    container_name: sharedgift-db
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/init.sh:/docker-entrypoint-initdb.d/init.sh
volumes:
  pgdata: